SELECT
    mic AS exchange_id,
    mic,
    operating_mic,
    mic_type,
    exchange_name,
    legal_entity_name,
    lei,
    market_category_code,
    acronym,
    country_iso2,
    city,
    website,
    status,
    creation_date,
    last_update_date,
    last_validation_date,
    expiry_date,
    comments,
    is_operating_mic,
    is_active,
    registry_provider,
    registry_snapshot_date,
    registry_ingested_at
FROM {{ ref('int_exchange_universe') }}
