SELECT
    isin_source,
    wkn_source,
    ticker_source,
    ticker_figi,
    name_figi,
    figi,
    share_class_figi,
    composite_figi,
    exchange_code_figi,
    security_type_figi,
    security_type2_figi,
    market_sector_figi,
    security_description_figi
FROM
    "mapping"."figi"
WHERE
    is_active;

