version: 2

models:
  - name: stg_exchange
    description: "A starter dbt model"
    columns:
      - name: name
        description: "Name of the exchange"
        data_tests:
          - not_null
      - name: code
        description: "Code of the exchange as assigned by EOD Historical Data"
        data_tests:
          - unique
          - not_null
      - name: mic
        description: "MIC code of the exchange"
