WITH fundamental_profile AS (
    SELECT *
    FROM {{ ref('int_fundamental_instrument_profile') }}
),

final AS (
    SELECT
        {{ surrogate_key(["data_provider", "ticker"]) }} AS instrument_fundamental_profile_pk,
        data_provider,
        provider_exchange_code,
        ticker,
        code,
        instrument_type,
        instrument_family,
        instrument_name,
        primary_ticker,
        provider_listing_exchange_code,
        currency_code,
        currency_name,
        country_name,
        country_iso,
        isin,
        cusip,
        cik,
        lei,
        open_figi,
        employer_id_number,
        fiscal_year_end,
        sector,
        industry,
        gic_sector,
        gic_group,
        gic_industry,
        gic_sub_industry,
        home_category,
        web_url,
        logo_url,
        domicile,
        tracked_index_name,
        fund_company_name,
        fund_company_url,
        etf_url,
        dividend_paying_frequency,
        fund_category,
        fund_family,
        fund_style,
        is_delisted,
        shares_outstanding,
        shares_float,
        percent_insiders,
        percent_institutions,
        short_ratio,
        short_percent_outstanding,
        short_percent_float,
        full_time_employees,
        holdings_count,
        index_market_cap,
        ipo_date,
        delisted_date,
        fund_inception_date,
        fund_update_date,
        provider_updated_at,
        latest_snapshot_date,
        payload_hash,
        document_ingested_at
    FROM fundamental_profile
)

SELECT * FROM final
