#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
    CREATE USER $DB_ADMIN_USER WITH PASSWORD '$DB_ADMIN_PASSWORD';
    CREATE USER $DB_APP_USER WITH PASSWORD '$DB_APP_PASSWORD';
    DROP DATABASE IF EXISTS $DB_NAME;
    CREATE database $DB_NAME
        WITH
        OWNER = $DB_ADMIN_USER
        ENCODING = 'UTF8'
        LC_COLLATE = 'en_US.utf8'
        LC_CTYPE = 'en_US.utf8'
        TABLESPACE = pg_default
        CONNECTION LIMIT = -1
        IS_TEMPLATE = False;

    REVOKE CONNECT ON DATABASE $DB_NAME FROM PUBLIC;
    GRANT  CONNECT ON DATABASE $DB_NAME  TO $DB_ADMIN_USER;
    GRANT  CONNECT ON DATABASE $DB_NAME  TO $DB_APP_USER;
    \c $DB_NAME postgres
    BEGIN;
        DROP SCHEMA IF EXISTS public CASCADE;
    COMMIT;
    \c $DB_NAME $DB_ADMIN_USER
    BEGIN;
        CREATE SCHEMA $DB_SCHEMA AUTHORIZATION $DB_ADMIN_USER;

        REVOKE ALL ON SCHEMA $DB_SCHEMA FROM PUBLIC;
        GRANT ALL ON SCHEMA $DB_SCHEMA TO $DB_ADMIN_USER;
        GRANT USAGE ON SCHEMA $DB_SCHEMA TO $DB_APP_USER;

        REVOKE ALL ON ALL TABLES IN SCHEMA $DB_SCHEMA FROM PUBLIC;
        GRANT ALL ON ALL TABLES IN SCHEMA $DB_SCHEMA TO $DB_ADMIN_USER;
        GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA $DB_SCHEMA TO $DB_APP_USER;

        ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_SCHEMA GRANT INSERT, SELECT, UPDATE ON TABLES TO $DB_APP_USER;
        ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_SCHEMA GRANT USAGE ON SEQUENCES TO $DB_APP_USER;
        ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_SCHEMA GRANT EXECUTE ON FUNCTIONS TO $DB_APP_USER;
    COMMIT;
EOSQL