#!/bin/bash
set -e

DB_NAME="app"

DB_SCHEMA_MIGRATION="migration"
DB_SCHEMA_DATA="data"



psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
    DROP DATABASE IF EXISTS $DB_NAME;
    CREATE database $DB_NAME
        WITH
        OWNER = $DB_ADMIN_USER
        ENCODING = 'UTF8'
        LC_COLLATE = 'en_US.utf8'
        LC_CTYPE = 'en_US.utf8'
        TABLESPACE = pg_default
        CONNECTION LIMIT = -1
        IS_TEMPLATE = False;
        
    ALTER DATABASE $DB_NAME SET timezone TO 'UTC';

    REVOKE CONNECT ON DATABASE $DB_NAME FROM PUBLIC;
    GRANT  CONNECT ON DATABASE $DB_NAME  TO $DB_ADMIN_USER;
    GRANT  CONNECT ON DATABASE $DB_NAME  TO $DB_APP_USER;

    \c $DB_NAME postgres
    BEGIN;
        DROP SCHEMA IF EXISTS public CASCADE;
    COMMIT;



    \c $DB_NAME $DB_ADMIN_USER

    BEGIN;
        CREATE SCHEMA $DB_SCHEMA_MIGRATION AUTHORIZATION $DB_ADMIN_USER;

        REVOKE ALL ON SCHEMA $DB_SCHEMA_MIGRATION FROM PUBLIC;

        REVOKE ALL ON ALL TABLES IN SCHEMA $DB_SCHEMA_MIGRATION FROM PUBLIC;
        GRANT ALL ON ALL TABLES IN SCHEMA $DB_SCHEMA_MIGRATION TO $DB_ADMIN_USER;
    COMMIT;

    BEGIN;
        CREATE SCHEMA $DB_SCHEMA_DATA AUTHORIZATION $DB_ADMIN_USER;

        REVOKE ALL ON SCHEMA $DB_SCHEMA_DATA FROM PUBLIC;
        GRANT ALL ON SCHEMA $DB_SCHEMA_DATA TO $DB_ADMIN_USER;
        GRANT USAGE ON SCHEMA $DB_SCHEMA_DATA TO $DB_APP_USER;

        REVOKE ALL ON ALL TABLES IN SCHEMA $DB_SCHEMA_DATA FROM PUBLIC;
        GRANT ALL ON ALL TABLES IN SCHEMA $DB_SCHEMA_DATA TO $DB_ADMIN_USER;
        GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA $DB_SCHEMA_DATA TO $DB_APP_USER;

        ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_SCHEMA_DATA GRANT INSERT, SELECT, UPDATE ON TABLES TO $DB_APP_USER;
        ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_SCHEMA_DATA GRANT USAGE ON SEQUENCES TO $DB_APP_USER;
        ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_SCHEMA_DATA GRANT EXECUTE ON FUNCTIONS TO $DB_APP_USER;
    COMMIT;
EOSQL
