version: '3.8'

services:
    db:
        container_name: unique-stocks-db-pg
        image: postgres:14.5-alpine
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
            - DB_PORT=${DB_PORT}
            - DB_ADMIN_USER=${DB_ADMIN_USER}
            - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
            - DB_APP_USER=${DB_APP_USER}
            - DB_APP_PASSWORD=${DB_APP_PASSWORD}
        volumes:
            - ./scripts/db:/docker-entrypoint-initdb.d/
            - unique-stocks-pg-data:/var/lib/postgresql/data/
        networks:
            - unique-stocks-network

volumes:
    unique-stocks-pg-data:
        name: "unique-stocks-pg-data"

networks:
    unique-stocks-network:
        name: unique-stocks-network
        external: true
