version: '3.8'

services:
    db:
        container_name: unique-stocks-db-pg
        image: postgres:14.5-alpine
        ports:
            - '${DB_PORT}:5432'
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_SCHEMA=${DB_SCHEMA}
            - DB_ADMIN_USER=${DB_ADMIN_USER}
            - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
            - DB_APP_USER=${DB_APP_USER}
            - DB_APP_PASSWORD=${DB_APP_PASSWORD}
        volumes:
            - ./db/scripts:/docker-entrypoint-initdb.d/
            - pg-data:/var/lib/postgresql/data/
        networks:
            - unique-stocks-network

volumes:
    pg-data:

networks:
    unique-stocks-network:
        name: unique-stocks-network
        external: true
