version: '3.8'

services:
    frontend:
        env_file:
            - .env
        restart: always
        build:
            context: .
            dockerfile: docker/Dockerfile.dev
        ports:
        - "3000:3000"
        stdin_open: true
        volumes:
            # Maps our current project directory `.` to
            # our working directory in the container
            - ./:/app/
            # node_modules workaround for volumes
            # https://stackoverflow.com/a/32785014
            - /app/node_modules