# stage base
FROM node:18-alpine3.15 as base

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY . .

RUN npm run build

# stage prod
FROM node:18-alpine3.15 as prod

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY --from=base /app/dist ./src

# EXPOSE 8000

CMD ["node", "src/server.js"]