name: unique_stocks
version: "1.0.0"
config-version: 2

profile: unique_stocks

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  unique_stocks:
    +materialized: view
    staging:
      +schema: silver
      +materialized: view
      +tags:
        - silver
    intermediate:
      +schema: silver
      +materialized: view
      +tags:
        - silver
    marts:
      +schema: gold
      +materialized: table
      +tags:
        - gold
