version: '3.8'

services:
    dremio:
        container_name: uniquestocks-lakehouse
        image: dremio/dremio-oss:latest
        ports:
            - 9047:9047
            - 31010:31010
            - 32010:32010
